#!/bin/bash
set -e

INSTANCE="${KOHA_INSTANCE:-edubox}"
DB_HOST="${KOHA_DB_HOST:-mariadb}"
DB_NAME="${KOHA_DB_NAME:-koha}"
DB_USER="${KOHA_DB_USER:-koha}"
DB_PASS="${KOHA_DB_PASS:-koha}"
DB_ROOT_PASS="${KOHA_DB_ROOT_PASS:-}"
MEMCACHED="${MEMCACHED_SERVER:-memcached:11211}"

echo "[EduBox Koha] Starting instance: $INSTANCE"

# mpm_itk is required by koha-create to generate config files
# (it checks for mpm_itk and refuses to run without it)
# We will switch to mpm_prefork AFTER koha-create has run
a2enmod mpm_itk 2>/dev/null || true

# Enable required Apache modules
a2enmod headers proxy_http rewrite deflate expires cgi 2>/dev/null || true

# Set Apache ports BEFORE koha-create (it restarts Apache during init)
printf 'Listen 8080\nListen 8081\n' > /etc/apache2/ports.conf

# Wait for MariaDB
echo "[EduBox Koha] Waiting for MariaDB at $DB_HOST:3306..."
for i in $(seq 1 60); do
    if mysqladmin ping -h "$DB_HOST" -u "$DB_USER" -p"$DB_PASS" --silent 2>/dev/null; then
        echo "[EduBox Koha] MariaDB is ready"
        break
    fi
    [ "$i" -eq 60 ] && { echo "[EduBox Koha] ERROR: MariaDB not ready after 60 tries"; exit 1; }
    echo "[EduBox Koha] Waiting for DB... ($i/60)"
    sleep 5
done

# Ensure koha DB and user exist (MariaDB init scripts only run on first start)
# If MariaDB data volume was pre-existing, the koha DB/user may not exist yet
if ! mysql -h "$DB_HOST" -u "$DB_USER" -p"$DB_PASS" -e "SELECT 1" "$DB_NAME" &>/dev/null; then
    echo "[EduBox Koha] koha DB not accessible, attempting to create..."
    if [ -n "$DB_ROOT_PASS" ]; then
        mysql -h "$DB_HOST" -u root -p"$DB_ROOT_PASS" <<SQLEOF 2>&1 || true
CREATE DATABASE IF NOT EXISTS \`$DB_NAME\` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS '$DB_USER'@'%' IDENTIFIED BY '$DB_PASS';
ALTER USER '$DB_USER'@'%' IDENTIFIED BY '$DB_PASS';
GRANT ALL PRIVILEGES ON \`$DB_NAME\`.* TO '$DB_USER'@'%';
FLUSH PRIVILEGES;
SQLEOF
        echo "[EduBox Koha] koha DB/user setup done"
    else
        echo "[EduBox Koha] WARNING: KOHA_DB_ROOT_PASS not set, cannot create DB automatically"
    fi
fi

# Pre-create data and runtime dirs
# NOTE: do NOT pre-create the system user — koha-create creates it as $INSTANCE-koha
# NOTE: do NOT pre-create /var/log/koha/$INSTANCE here — koha-create does mkdir (not mkdir -p)
#       and set -e causes it to abort if the dir already exists.
#       The log dir is created after koha-create (or after skipping it) below.
mkdir -p \
    "/var/run/koha/$INSTANCE" \
    "/var/lock/koha/$INSTANCE" \
    "/var/lib/koha/$INSTANCE/biblios" \
    "/var/lib/koha/$INSTANCE/authorities" \
    "/var/lib/koha/$INSTANCE/plugins" \
    "/var/lib/koha/$INSTANCE/uploads" \
    "/tmp/koha-$INSTANCE"

# Create Koha instance if not already configured (volume-persisted check)
# Also re-run if Apache site config is missing (not persisted — lost on container recreation)
if [ ! -f "/etc/koha/sites/$INSTANCE/koha-conf.xml" ] || [ ! -f "/etc/apache2/sites-available/$INSTANCE.conf" ]; then
    echo "[EduBox Koha] Running koha-create --use-db for instance: $INSTANCE"

    # passwdfile format: instancename:username:password:dbname:dbhost
    printf '%s:%s:%s:%s:%s\n' "$INSTANCE" "$DB_USER" "$DB_PASS" "$DB_NAME" "$DB_HOST" \
        > /tmp/koha-passwd
    chmod 600 /tmp/koha-passwd

    # --use-db: uses existing DB (created by MariaDB init script)
    # Generates: koha-conf.xml, zebra configs, log4perl.conf, Apache site config
    # Side effects: creates system user $INSTANCE-koha, starts Apache/Zebra/Plack
    koha-create --use-db \
        --dbhost "$DB_HOST" \
        --database "$DB_NAME" \
        --passwdfile /tmp/koha-passwd \
        --memcached-servers "$MEMCACHED" \
        --memcached-prefix "koha_$INSTANCE" \
        "$INSTANCE" 2>&1 | sed 's/^/[koha-create] /' || \
        echo "[EduBox Koha] koha-create done (see above)"

    rm -f /tmp/koha-passwd
fi

# Create log dir after koha-create (koha-create uses mkdir without -p + set -e,
# so it must not exist when koha-create runs; on subsequent runs koha-create is
# skipped, so we create it here unconditionally)
mkdir -p "/var/log/koha/$INSTANCE"

# The Koha system user created by koha-create is $INSTANCE-koha
KOHA_USER="${INSTANCE}-koha"

# Fix ownership of runtime dirs (user now exists after koha-create)
if id "$KOHA_USER" &>/dev/null; then
    chown -R "$KOHA_USER:" \
        "/var/lib/koha/$INSTANCE" \
        "/var/run/koha/$INSTANCE" \
        "/var/lock/koha/$INSTANCE" 2>/dev/null || true
    chown -R "$KOHA_USER:" "/var/log/koha/$INSTANCE" 2>/dev/null || true
fi

# Fix koha-conf.xml generated by koha-create
KOHA_CONF="/etc/koha/sites/$INSTANCE/koha-conf.xml"
if [ -f "$KOHA_CONF" ]; then
    # Remove DOCTYPE (causes DTD lookup failure in Docker)
    sed -i '/<!DOCTYPE/d' "$KOHA_CONF"

    # Fix DB hostname (template defaults to localhost, we need the container name)
    sed -i "s|<hostname>.*</hostname>|<hostname>$DB_HOST</hostname>|g" "$KOHA_CONF"

    # Ensure DB password is correct
    sed -i "s|<pass>.*</pass>|<pass>$DB_PASS</pass>|g" "$KOHA_CONF"

    # Configure Memcached
    if grep -q '<memcached_servers>' "$KOHA_CONF"; then
        sed -i "s|<memcached_servers>.*</memcached_servers>|<memcached_servers>$MEMCACHED</memcached_servers>|g" "$KOHA_CONF"
    fi

    echo "[EduBox Koha] koha-conf.xml updated"
fi

# Fix Apache config: remove AssignUserID (requires mpm_itk, not suitable for Docker root)
APACHE_CONF="/etc/apache2/sites-available/$INSTANCE.conf"
if [ -f "$APACHE_CONF" ]; then
    sed -i '/AssignUserID/d' "$APACHE_CONF"
    echo "[EduBox Koha] Apache config: AssignUserID removed"
    # Accept any Host header — nginx proxies with the original client's Host (e.g. 192.168.0.147)
    # Without ServerAlias *, Apache falls back to the default site (blank Apache page)
    sed -i '/ServerName/a\    ServerAlias *' "$APACHE_CONF"
    echo "[EduBox Koha] Apache config: ServerAlias * added"
fi

# Ensure Koha site is enabled and default site is disabled
# koha-create does a2ensite but the symlink may be missing after container recreation
a2ensite "$INSTANCE" 2>/dev/null || true
a2dissite 000-default 2>/dev/null || true
echo "[EduBox Koha] Apache: a2ensite $INSTANCE + a2dissite 000-default"

# ── Auto-setup schéma et superlibrarian (premier démarrage) ──────────────────
INSTALLER_DIR="/usr/share/koha/intranet/cgi-bin/installer/data/mysql"

SCHEMA_OK=$(mysql -h "$DB_HOST" -u "$DB_USER" -p"$DB_PASS" "$DB_NAME" \
    -N -e "SELECT 1 FROM information_schema.tables \
           WHERE table_schema='$DB_NAME' AND table_name='systempreferences' LIMIT 1;" \
    2>/dev/null || echo "")

if [ "$SCHEMA_OK" != "1" ]; then
    echo "[EduBox Koha] Installing database schema (first run)..."

    if [ -f "$INSTALLER_DIR/kohastructure.sql" ]; then
        mysql -h "$DB_HOST" -u "$DB_USER" -p"$DB_PASS" "$DB_NAME" \
            < "$INSTALLER_DIR/kohastructure.sql" 2>&1 | sed 's/^/[koha-schema] /' || true
        echo "[EduBox Koha] kohastructure.sql imported"
    else
        echo "[EduBox Koha] WARNING: kohastructure.sql not found at $INSTALLER_DIR"
    fi

    if [ -d "$INSTALLER_DIR/mandatory" ]; then
        for sql_f in "$INSTALLER_DIR/mandatory/"*.sql; do
            [ -f "$sql_f" ] && \
                mysql -h "$DB_HOST" -u "$DB_USER" -p"$DB_PASS" "$DB_NAME" \
                    < "$sql_f" 2>/dev/null || true
        done
        echo "[EduBox Koha] Mandatory data imported"
    fi
fi

ADMIN_COUNT=$(mysql -h "$DB_HOST" -u "$DB_USER" -p"$DB_PASS" "$DB_NAME" \
    -N -e "SELECT COUNT(*) FROM borrowers WHERE flags & 1 = 1;" 2>/dev/null || echo 0)

if [ "${ADMIN_COUNT:-0}" -eq 0 ]; then
    echo "[EduBox Koha] Creating superlibrarian (koha_admin)..."
    PERL5LIB=/usr/share/koha/lib \
    KOHA_CONF="$KOHA_CONF" \
        perl /usr/local/bin/koha-setup-admin.pl "${KOHA_ADMIN_PASS:-koha_admin}" \
        2>&1 | sed 's/^/[koha-admin] /' || \
        echo "[EduBox Koha] WARNING: admin creation failed — manual setup may be needed"
fi

# Set Version systempreference to match the installed Koha version.
# Koha Auth.pm transforms the version string with s/(.*\..*)\.(.*)\.(.*)/$1$2$3/
# before numeric comparison, so we must store the same transformed format.
# e.g. "25.11.04.000" → "25.1104000" (otherwise 25.11 < 25.1104 → maintenance loop).
KOHA_VER=$(PERL5LIB=/usr/share/koha/lib KOHA_CONF="$KOHA_CONF" \
    perl -e 'use Koha; my $v=Koha::version(); $v=~s/(.*\..*)\.(.*)\.(.*)/$1$2$3/; print $v;' \
    2>/dev/null || echo "")
if [ -n "$KOHA_VER" ]; then
    mysql -h "$DB_HOST" -u "$DB_USER" -p"$DB_PASS" "$DB_NAME" \
        -e "INSERT INTO systempreferences (variable,value,options,explanation,type)
            VALUES ('Version','$KOHA_VER',NULL,NULL,'Free')
            ON DUPLICATE KEY UPDATE value='$KOHA_VER';" 2>/dev/null && \
        echo "[EduBox Koha] Version pref set to $KOHA_VER" || true
fi
# ─────────────────────────────────────────────────────────────────────────────

# Enable Plack (uncomments the Include plack lines in Apache config)
koha-plack --enable "$INSTANCE" 2>&1 | sed 's/^/[koha-plack] /' || true

# Switch from mpm_itk to mpm_prefork (mpm_itk initgroups fails in Docker)
# This is done AFTER koha-create since koha-create requires mpm_itk
a2dismod mpm_itk 2>/dev/null || true
a2enmod mpm_prefork 2>/dev/null || true
echo "[EduBox Koha] Apache MPM: switched to mpm_prefork"

# Stop services started by koha-create — supervisord will manage them cleanly
# Apache: supervisord runs it in foreground mode (apache2ctl -D FOREGROUND)
# Zebra/Plack/SIP: supervisord starts their daemon launchers once (autorestart=false)
echo "[EduBox Koha] Stopping koha-create-started services (supervisord will restart)..."
apache2ctl graceful-stop 2>/dev/null || pkill -f apache2 2>/dev/null || true
koha-plack --stop "$INSTANCE" 2>/dev/null || true
koha-zebra --stop "$INSTANCE" 2>/dev/null || true
sleep 2

# Pre-create all log files with correct ownership BEFORE supervisord starts Apache.
# koha-create does NOT start Apache here (httpd not running), so opac-error.log
# and intranet-error.log don't exist yet. Without this, Apache (root) creates them
# and Plack (edubox-koha) gets Permission denied when trying to write.
KOHA_USER="${INSTANCE}-koha"
for logfile in opac-error.log intranet-error.log zebra.log sip.log; do
    touch "/var/log/koha/$INSTANCE/$logfile"
done
chown -R "$KOHA_USER:" "/var/log/koha/$INSTANCE/"
chmod 664 /var/log/koha/"$INSTANCE"/*.log
chmod 775 "/var/log/koha/$INSTANCE/"
echo "[EduBox Koha] Log files pre-created and owned by $KOHA_USER"

echo "[EduBox Koha] Starting supervisord..."
exec "$@"
