# Configuration des sites Koha
# Variables d'environnement surchargées par entrypoint.sh

<listen>
    <item>*:8080</item>
    <item>*:8081</item>
</listen>

<serveralias>edubox</serveralias>
<intranetport>8081</intranetport>
<opacport>8080</opacport>
<defaultsites>/etc/koha/sites</defaultsites>
