[supervisord]
nodaemon=false
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid
user=root

[program:koha-plack-opac]
command=koha-plack --start %(ENV_KOHA_INSTANCE)s
autorestart=true
stderr_logfile=/var/log/koha/%(ENV_KOHA_INSTANCE)s/plack-opac.log
stdout_logfile=/var/log/koha/%(ENV_KOHA_INSTANCE)s/plack-opac.log
priority=20

[program:koha-plack-intra]
command=koha-plack --start %(ENV_KOHA_INSTANCE)s --intranet
autorestart=true
stderr_logfile=/var/log/koha/%(ENV_KOHA_INSTANCE)s/plack-intra.log
stdout_logfile=/var/log/koha/%(ENV_KOHA_INSTANCE)s/plack-intra.log
priority=20

[program:apache2]
command=/usr/sbin/apache2ctl -D FOREGROUND
autorestart=true
stderr_logfile=/var/log/apache2/error.log
stdout_logfile=/var/log/apache2/access.log
priority=10

[program:zebra]
command=koha-zebra --start %(ENV_KOHA_INSTANCE)s
autorestart=true
stderr_logfile=/var/log/koha/%(ENV_KOHA_INSTANCE)s/zebra.log
stdout_logfile=/var/log/koha/%(ENV_KOHA_INSTANCE)s/zebra.log
priority=15

[program:koha-sip]
command=koha-sip --start %(ENV_KOHA_INSTANCE)s
autorestart=true
stderr_logfile=/var/log/koha/%(ENV_KOHA_INSTANCE)s/sip.log
stdout_logfile=/var/log/koha/%(ENV_KOHA_INSTANCE)s/sip.log
priority=25
