#!/bin/bash
set -e

DB_HOST="${SLIMS_DB_HOST:-mariadb}"
DB_NAME="${SLIMS_DB_NAME:-slims}"
DB_USER="${SLIMS_DB_USER:-slims}"
DB_PASS="${SLIMS_DB_PASS:-slims}"
ADMIN_PASS="${SLIMS_ADMIN_PASS:-admin}"
SLIMS_ROOT="/var/www/html/slims"
MARKER="$SLIMS_ROOT/config/.slims_initialized"

echo "[SLiMS] Starting entrypoint..."

# Wait for MariaDB
echo "[SLiMS] Waiting for MariaDB at $DB_HOST..."
for i in $(seq 1 40); do
    if mysqladmin ping -h "$DB_HOST" -u "$DB_USER" -p"$DB_PASS" --silent 2>/dev/null; then
        echo "[SLiMS] MariaDB ready"
        break
    fi
    [ "$i" -eq 40 ] && { echo "[SLiMS] ERROR: MariaDB not ready after 120s"; exit 1; }
    sleep 3
done

# Write database.php — SLiMS 9.7.x uses a PHP-array config (based on database.sample.php)
cat > "$SLIMS_ROOT/config/database.php" <<PHPEOF
<?php
// Generated by Ofelia entrypoint — do not edit manually
return [
    'default_profile' => 'SLiMS',
    'proxy' => false,
    'nodes' => [
        'SLiMS' => [
            'host'     => '$DB_HOST',
            'database' => '$DB_NAME',
            'port'     => '3306',
            'username' => '$DB_USER',
            'password' => '$DB_PASS',
            'options'  => ['storage_engine' => 'InnoDB'],
        ],
    ],
];
PHPEOF
echo "[SLiMS] database.php written"

# Install schema and set admin password (first run only)
if [ ! -f "$MARKER" ]; then
    TABLES=$(mysql -h "$DB_HOST" -u "$DB_USER" -p"$DB_PASS" "$DB_NAME" \
        -N -e "SELECT COUNT(*) FROM information_schema.tables WHERE table_schema='$DB_NAME';" \
        2>/dev/null || echo 0)

    if [ "${TABLES:-0}" -lt 5 ]; then
        echo "[SLiMS] Installing database schema..."

        # Import senayan_ddl.sql FIRST (up-to-date DDL including deleted_at, options, etc.)
        # then senayan.sql : uses CREATE TABLE IF NOT EXISTS so DDL is skipped,
        # only INSERT statements run — giving us the default data.
        if [ -f "$SLIMS_ROOT/install/senayan_ddl.sql" ]; then
            echo "[SLiMS] Importing senayan_ddl.sql (DDL)..."
            mysql -h "$DB_HOST" -u "$DB_USER" -p"$DB_PASS" "$DB_NAME" \
                < "$SLIMS_ROOT/install/senayan_ddl.sql"
        fi
        if [ -f "$SLIMS_ROOT/install/senayan.sql" ]; then
            echo "[SLiMS] Importing senayan.sql (data)..."
            mysql -h "$DB_HOST" -u "$DB_USER" -p"$DB_PASS" "$DB_NAME" \
                < "$SLIMS_ROOT/install/senayan.sql"
        fi

        echo "[SLiMS] Schema installed"
    else
        echo "[SLiMS] Schema already present ($TABLES tables) — skipping import"
    fi

    # Set admin password (SLiMS 9.x stores passwords as MD5)
    mysql -h "$DB_HOST" -u "$DB_USER" -p"$DB_PASS" "$DB_NAME" \
        -e "UPDATE user SET passwd=MD5('$ADMIN_PASS') WHERE username='admin';" \
        2>/dev/null && echo "[SLiMS] Admin password set" || true

    touch "$MARKER"
fi

echo "[SLiMS] Starting Apache..."
exec apache2-foreground
