const t = {
	fr: {
		sondage: 'Sondage',
		remueMeninges: 'Remue-méninges',
		questionnaire: 'Questionnaire',
		nuageDeMots: 'Nuage de mots',
		question: 'Question',
		reponses: 'Réponses',
		demarre: 'Démarré',
		termine: 'Terminé',
		progression: 'Progression :',
		progressionLibre: 'Libre',
		progressionAnimateur: 'Gérée par l\'animateur',
		bonneReponse: 'Réponse correcte',
		classement: 'Classement',
		points: 'points',
		description: 'Description',
		support: 'Support',
		image: 'Image :',
		fichierAudio: 'Fichier audio :',
		video: 'Vidéo',
		code: 'Code :',
		lien: 'Lien pour les participants :',
		lienAdmin: 'Lien d\'administration :',
		motdepasse: 'Mot de passe d\'administration :',
		messagesSupprimes: 'Messages supprimés',
		motsSupprimes: 'Mots supprimés',
		copieDe: 'Copie de ',
		moyenne: 'Moyenne : '
	},
	en: {
		sondage: 'Survey',
		remueMeninges: 'Brainstorm',
		questionnaire: 'Quiz',
		nuageDeMots: 'Wordcloud',
		question: 'Question',
		reponses: 'Answers',
		demarre: 'Started',
		termine: 'Ended',
		progression: 'Progression:',
		progressionLibre: 'Free',
		progressionAnimateur: 'Managed by the host',
		bonneReponse: 'Correct answer',
		classement: 'Ranking',
		points: 'points',
		description: 'Description',
		support: 'Media',
		image: 'Image:',
		fichierAudio: 'Audio file:',
		video: 'Video:',
		code: 'Code:',
		lien: 'Link for participants:',
		lienAdmin: 'Link for administration:',
		motdepasse: 'Administration password:',
		messagesSupprimes: 'Deleted messages',
		motsSupprimes: 'Deleted words',
		copieDe: 'Copy of ',
		moyenne: 'Average: '
	},
	es: {
		sondage: 'Sondeo',
		remueMeninges: 'Lluvia de ideas',
		questionnaire: 'Cuestionario',
		nuageDeMots: 'Nube de palabras',
		question: 'Pregunta',
		reponses: 'Respuestas',
		demarre: 'Comenzó',
		termine: 'Finaliza',
		progression: 'Progresión:',
		progressionLibre: 'Libre',
		progressionAnimateur: 'Gestionada por el organizador',
		bonneReponse: 'Respuesta correcta',
		classement: 'Clasificación del cuestionario',
		points: 'Puntuación',
		description: 'Descripción',
		support: 'Ayuda',
		image: 'Imagen:',
		fichierAudio: 'Archivo de audio:',
		video: 'Video:',
		code: 'Código:',
		lien: 'Enlace para los participantes:',
		lienAdmin: 'Enlace de la administración:',
		motdepasse: 'Contraseña de administración:',
		messagesSupprimes: 'Mensajes borrados',
		motsSupprimes: 'Palabras borradas',
		copieDe: 'Copia de ',
		moyenne: 'Media: '
	},
	it: {
		sondage: 'Sondaggio',
		remueMeninges: 'Brainstorming',
		questionnaire: 'Questionario',
		nuageDeMots: 'Nuvola di parole',
		question: 'Domanda',
		reponses: 'Risposta',
		demarre: 'Inizia',
		termine: 'Finisci',
		progression: 'Flusso:',
		progressionLibre: 'Libero',
		progressionAnimateur: 'Gestito dal conduttore',
		bonneReponse: 'Risposta esatta',
		classement: 'Classifica',
		points: 'punti',
		description: 'Descrizione',
		support: 'Media',
		image: 'Immagine:',
		fichierAudio: 'File audio:',
		video: 'Video:',
		code: 'Codice:',
		lien: 'Link per i partecipanti:',
		lienAdmin: 'Link per l\'amministrazione:',
		motdepasse: 'Password per l\'amministrazione:',
		messagesSupprimes: 'Messaggi eliminati',
		motsSupprimes: 'Parole eliminate',
		copieDe: 'Copia di ',
		moyenne: 'Media: '
	},
	de: {
		sondage: 'Umfrage',
		remueMeninges: 'Brainstorming',
		questionnaire: 'Quiz',
		nuageDeMots: 'Wortwolke',
		question: 'Frage',
		reponses: 'Antworten',
		demarre: 'Gestartet',
		termine: 'Beendet',
		progression: 'Fortschritt:',
		progressionLibre: 'Frei',
		progressionAnimateur: 'Vom Moderator verwaltet',
		bonneReponse: 'Richtige Antwort',
		classement: 'Quiz-Rangliste',
		points: 'Punkte',
		description: 'Beschreibung',
		support: 'Unterstützung',
		image: 'Bild:',
		fichierAudio: 'Audiodatei:',
		video: 'Video',
		code: 'Code:',
		lien: 'Link für Teilnehmer:',
		lienAdmin: 'Link zur Verwaltung:',
		motdepasse: 'Administrator-Passwort:',
		messagesSupprimes: 'Gelöschte Postings',
		motsSupprimes: 'Gelöschte Wörter',
		copieDe: 'Kopie von ',
		moyenne: 'Durchschnitt: '
	}
}

export default t
