#!/bin/bash
set -e

DB_HOST="${PMB_DB_HOST:-mariadb}"
DB_NAME="${PMB_DB_NAME:-pmb}"
DB_USER="${PMB_DB_USER:-pmb}"
DB_PASS="${PMB_DB_PASS:-pmb}"
ADMIN_PASS="${PMB_ADMIN_PASS:-admin}"
PMB_ROOT="/var/www/html/pmb"
MARKER="$PMB_ROOT/includes/.pmb_initialized"

echo "[PMB] Starting entrypoint..."

# Wait for MariaDB
echo "[PMB] Waiting for MariaDB at $DB_HOST..."
for i in $(seq 1 40); do
    if mysqladmin ping -h "$DB_HOST" -u "$DB_USER" -p"$DB_PASS" --silent 2>/dev/null; then
        echo "[PMB] MariaDB ready"
        break
    fi
    [ "$i" -eq 40 ] && { echo "[PMB] ERROR: MariaDB not ready after 120s"; exit 1; }
    sleep 3
done

# Write db_param.inc.php — PMB 8.x uses define() constants (SQL_SERVER, USER_NAME, etc.)
# This file is included by init.inc.php via global_vars.inc.php
cat > "$PMB_ROOT/includes/db_param.inc.php" <<PHPEOF
<?php
// Generated by Ofelia entrypoint — do not edit manually
if (preg_match('/db_param\.inc\.php/', \$_SERVER['REQUEST_URI'] ?? '')) {
    include('./forbidden.inc.php'); exit;
}
\$_tableau_databases[0] = '$DB_NAME';
\$_libelle_databases[0] = 'EduBox';
if (empty(\$database)) {
    \$database = !empty(\$_COOKIE['PhpMyBibli-DATABASE']) ? \$_COOKIE['PhpMyBibli-DATABASE'] : \$_tableau_databases[0];
}
if (!in_array(\$database, \$_tableau_databases)) \$database = \$_tableau_databases[0];
define('LOCATION', \$database);
switch (LOCATION) {
    default:
    case '$DB_NAME':
        define('SQL_SERVER', '$DB_HOST');
        define('USER_NAME',  '$DB_USER');
        define('USER_PASS',  '$DB_PASS');
        define('DATA_BASE',  '$DB_NAME');
        define('SQL_TYPE',   'mysql');
        \$charset = 'utf-8';
        break;
}
\$dsn_pear = SQL_TYPE.'://'.USER_NAME.':'.USER_PASS.'@'.SQL_SERVER.'/'.DATA_BASE;
PHPEOF
echo "[PMB] db_param.inc.php written"

# Write opac_db_param.inc.php — required by the OPAC (opac_css/) interface
cat > "$PMB_ROOT/opac_css/includes/opac_db_param.inc.php" <<PHPEOF
<?php
// Generated by Ofelia entrypoint — do not edit manually
if (preg_match('/opac_db_param\.inc\.php/', \$_SERVER['REQUEST_URI'] ?? '')) {
    include('./forbidden.inc.php'); exit;
}
\$_tableau_databases[0] = '$DB_NAME';
\$_libelle_databases[0] = 'EduBox';
if (empty(\$database)) {
    \$database = !empty(\$_COOKIE['PhpMyBibli-OPACDB']) ? \$_COOKIE['PhpMyBibli-OPACDB'] :
                 (!empty(\$_COOKIE['PhpMyBibli-DATABASE']) ? \$_COOKIE['PhpMyBibli-DATABASE'] : \$_tableau_databases[0]);
}
if (!in_array(\$database, \$_tableau_databases)) \$database = \$_tableau_databases[0];
define('LOCATION', \$database);
switch (LOCATION) {
    default:
    case '$DB_NAME':
        define('SQL_SERVER', '$DB_HOST');
        define('USER_NAME',  '$DB_USER');
        define('USER_PASS',  '$DB_PASS');
        define('DATA_BASE',  '$DB_NAME');
        define('SQL_TYPE',   'mysql');
        \$charset = 'utf-8';
        break;
}
\$dsn_pear = SQL_TYPE.'://'.USER_NAME.':'.USER_PASS.'@'.SQL_SERVER.'/'.DATA_BASE;
PHPEOF
echo "[PMB] opac_db_param.inc.php written"

# Install schema and set admin password (first run only)
if [ ! -f "$MARKER" ]; then
    TABLES=$(mysql -h "$DB_HOST" -u "$DB_USER" -p"$DB_PASS" "$DB_NAME" \
        -N -e "SELECT COUNT(*) FROM information_schema.tables WHERE table_schema='$DB_NAME';" \
        2>/dev/null || echo 0)

    if [ "${TABLES:-0}" -lt 5 ]; then
        echo "[PMB] Installing database schema..."

        # PMB 8.x: main schema is tables/bibli.sql
        if [ -f "$PMB_ROOT/tables/bibli.sql" ]; then
            echo "[PMB] Importing bibli.sql..."
            mysql -h "$DB_HOST" -u "$DB_USER" -p"$DB_PASS" "$DB_NAME" < "$PMB_ROOT/tables/bibli.sql"
        fi

        # Locale data — ES preferred, FR fallback (minimum.sql + feed_essential.sql)
        for locale in es fr en; do
            LOCALE_DIR="$PMB_ROOT/tables/$locale"
            if [ -d "$LOCALE_DIR" ]; then
                for f in "$LOCALE_DIR/minimum.sql" "$LOCALE_DIR/feed_essential.sql"; do
                    [ -f "$f" ] && mysql -h "$DB_HOST" -u "$DB_USER" -p"$DB_PASS" "$DB_NAME" < "$f" 2>/dev/null
                done
                echo "[PMB] Locale data imported ($locale)"
                break
            fi
        done

        echo "[PMB] Schema installed"
    else
        echo "[PMB] Schema already present ($TABLES tables) — skipping import"
    fi

    # Set admin password (PMB 8.x stores passwords as MD5)
    # PMB login uses MySQL::password() = "*" . strtoupper(sha1(hex2bin(sha1($pass))))
    # MariaDB PASSWORD() produces a different hash — must compute in PHP
    PMB_HASH=$(ADMIN_PASS_VAL="$ADMIN_PASS" php -r \
        'echo "*".strtoupper(sha1(hex2bin(sha1(getenv("ADMIN_PASS_VAL")))));')
    mysql -h "$DB_HOST" -u "$DB_USER" -p"$DB_PASS" "$DB_NAME" \
        -e "UPDATE users SET pwd='$PMB_HASH', user_lang='es_ES' WHERE username='admin';" \
        2>/dev/null && echo "[PMB] Admin password set" || true

    touch "$MARKER"
fi

echo "[PMB] Starting Apache..."
exec apache2-foreground
