<?php
// Generated by Ofelia entrypoint — do not edit manually
if (preg_match('/opac_db_param\.inc\.php/', $_SERVER['REQUEST_URI'] ?? '')) {
    include('./forbidden.inc.php'); exit;
}
$_tableau_databases[0] = '__DB_NAME__';
$_libelle_databases[0] = 'EduBox';
if (empty($database)) {
    $database = !empty($_COOKIE['PhpMyBibli-OPACDB']) ? $_COOKIE['PhpMyBibli-OPACDB'] :
                 (!empty($_COOKIE['PhpMyBibli-DATABASE']) ? $_COOKIE['PhpMyBibli-DATABASE'] : $_tableau_databases[0]);
}
if (!in_array($database, $_tableau_databases)) $database = $_tableau_databases[0];
define('LOCATION', $database);
switch (LOCATION) {
    default:
    case '__DB_NAME__':
        define('SQL_SERVER', '__DB_HOST__');
        define('USER_NAME',  '__DB_USER__');
        define('USER_PASS',  '__DB_PASS__');
        define('DATA_BASE',  '__DB_NAME__');
        define('SQL_TYPE',   'mysql');
        $charset = 'utf-8';
        break;
}
$dsn_pear = SQL_TYPE.'://'.USER_NAME.':'.USER_PASS.'@'.SQL_SERVER.'/'.DATA_BASE;
